#!/bin/bash
API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

# Here, I'm clearing previous error logs
> "$ERROR_FILE"

#and then the API requests.....
HTTP_STATUS=$(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" "$API_URL")


if [ "$HTTP_STATUS" -ne 200 ]; then
    echo "[$(date)] Error: Failed to fetch Pikachu data. HTTP Status: $HTTP_STATUS" >> "$ERROR_FILE"
    rm -f "$OUTPUT_FILE"
    exit 1
fi

echo "✅ Pikachu data successfully saved to $OUTPUT_FILE"
